FROM python:3.10-slim

WORKDIR /workspace

COPY . .

RUN pip install --no-cache-dir torch==2.3.1 torchvision==0.18.1 \
        --index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir -r docker_light_requirements.txt \
    && pip install --no-cache-dir . --no-dependencies

ENV PROJECT_ROOT=/workspace