net:
  _target_: ascent.models.components.unet.UNet
  in_channels: 1
  num_classes: 2
  patch_size:
  - 352
  - 288
  - 20
  kernels:
  - - 3
    - 3
    - 1
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  - - 3
    - 3
    - 3
  strides:
  - - 1
    - 1
    - 1
  - - 2
    - 2
    - 1
  - - 2
    - 2
    - 2
  - - 2
    - 2
    - 2
  - - 2
    - 2
    - 1
  - - 2
    - 2
    - 1
  normalization_layer: instance
  negative_slope: 0.01
  deep_supervision: true
  attention: false
  drop_block: false
  residual: false
  out_seg_bias: false
optimizer:
  _target_: torch.optim.SGD
  _partial_: true
  lr: 0.01
  dampening: 0
  momentum: 0.99
  nesterov: true
  weight_decay: 3.0e-05
scheduler:
  _target_: ascent.utils.scheduler.poly_lr.PolynomialLR
  _partial_: true
  max_decay_steps: 1
loss:
  _target_: ascent.utils.loss_functions.dice_loss.DC_and_CE_loss
  soft_dice_kwargs:
    batch_dice: false
    smooth: 1.0e-05
    do_bg: false
  ce_kwargs: {}
  weight_ce: 1
  weight_dice: 1
_target_: ascent.models.nnunet_module.nnUNetLitModule
tta: false
save_predictions: false
save_npz: false
name: nnUNet
